# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Nzg2ZWU2ZGVlMTYwOGNhZGM1MTBkOTBiOWFlMmU1NzE4ZmJhYjMyYmJiMzAxMTJkNjEwYjNmMTNkMzFiMGE0ZWQ4MTA4ZDcwMmNhN2U5MjQ1MGY5ODA4YzdhOGIxMmRhNjFmYWViNWIxNWY0YTc5OGM0ZDEwYzJhOWU0ZjU3NDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
